package br.com.tiu.forum.domain.topico;

public enum Categoria {
    MATEMATICA,
    PORTUGUES,
    HISTORIA,
    GEOGRAFIA,
    CIENCIAS,
    FISICA,
    QUIMICA,
    BIOLOGIA,
    INGLES,
    LITERATURA,
    EDUCACAO_FISICA,
    DUVIDAS_DE_AULA,
    RESUMO_E_ANOTACOES,
    TRABALHOS_ESCOLARES,
    PROVAS_E_SIMULADOS,
    LIÇÃO_DE_CASA,
    CONTEUDO_EXTRA,
    TECNOLOGIA,
    CONVERSAS_GERAIS
}
